---
- name: Enable to amazon-linux-extras repogitory
  shell: "amazon-linux-extras enable nginx1.12"

- name: install nginx
  yum:
    name: nginx

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

